sudo: required

services:
  - docker

before_install:
  - docker build -t computervision:ubuntu18-cuda10 -f Dockerfile-ubuntu18-cuda10 .

script:
  - docker run computervision:ubuntu18-cuda10 /bin/bash -c "pdftoppm -v"
